app/posts/models.py
class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    subject = db.Column(db.String(50), unique=True, nullable=False)
    content = db.Column(db.String(500), unique=True, nullable=False)

    def __repr__(self):
        return f" Post ==> {self.subject}"

app/user/models.py
from app import db

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(30), unique=True, nullable=False)
    email = db.Column(db.String(50), unique=True, nullable=False)
    password = db.Column(db.String(30), unique=True, nullable=False)

    def __repr__(self):
        return f" User ==> {self.username}, {self.email}, {self.password}"

app/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import DataRequired, Length




class PostForm(FlaskForm):
    subject = StringField('subject', validators=[DataRequired(), Length(max=50)])
    content = StringField('content', validators=[DataRequired(), Length(max=500)])

app/user/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Length, Email


class RegisterForm(FlaskForm):
    username = StringField('user name', validators=[DataRequired(), Length(min=2, max=30)])
    email = StringField('email', validators=[DataRequired(), Email()])
    password = StringField('password', validators=[DataRequired(), Length(min=8, max=20)])
    submit = SubmitField('Sign up')


class LoginForm(FlaskForm):
    username = StringField('user name', validators=[DataRequired(), Length(min=2, max=30)])
    password = StringField('password', validators=[DataRequired(), Length(min=8, max=20)])
    login = SubmitField('login')

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from app.config import Configs

db = SQLAlchemy()

def create_app(config_class=Configs):
    app = Flask(__name__)
    app.config.from_object(Configs)
    db.init_app(app)

    from app.user.routes import users
    from app.posts.routes import posts
    from app.main.routes import main
    from app.errors.handlers import errors

    app.register_blueprint(users, url_prefix="/user")
    app.register_blueprint(posts, url_prefix="/post")
    app.register_blueprint(main)
    app.register_blueprint(errors, url_prefix="/errors")

    return app

app/main/routes.py
from flask import Blueprint


main = Blueprint("main", __name__)


@main.route('/about', methods=['POST', 'GET'])
def about():
    return 'About Page'

@main.route("/")
@main.route('/home', methods=['POST', 'GET'])
def home():
    return 'Home Page'

app/posts/routes.py
from flask import Blueprint

posts = Blueprint('posts',__name__)



@posts.route('/')
@posts.route('/home', methods=['GET', 'POST'])
def home():
    return 'hello world'

app/user/routes.py
from flask import Blueprint,redirect,url_for,render_template
from app.user.forms import RegisterForm, LoginForm
from app import db
from app.user.models import User

users = Blueprint('users', __name__)


@users.route('/signup', methods=['POST', 'GET'])
def signup():
    form = RegisterForm()
    if form.validate_on_submit():
        user = User(username=form.username.data, email=form.email.data, password=form.password.data)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('posts.home'))
    return render_template("register.html", title="Registration", form=form)


@users.route('/login', methods=['POST', 'GET'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and user.password == form.password.data:
            return redirect(url_for('posts.home'))
    return render_template("login.html", title="Login", form=form)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
     <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}"  crossorigin="anonymous">
    {% if title%}
        <title>app - {{ title }}</title>
    {% else %}
        <title>app </title>
    {% endif %}
</head>
<body>
<div class="container">
    {% block content %} {% endblock content %}
</div>
    <script src="{{ url_for('static', filename='js/bootstrap.min.ks') }}" crossorigin="anonymous"></script>


</body>
</html>

app/templates/home.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section">
        <h1> in side Home </h1>
    </div>

{% endblock content %}

app/templates/login.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <legend> Login </legend>
            <div class="form-group">
                {{form.username.label(class="form-control-label")}}
                {{form.username(class="form-control form-control-lg")}}
            </div>
            <div class="form-group">
                {{form.password.label(class="form-control-label")}}
                {{form.password(class="form-control form-control-lg")}}
            </div>
            <div class="form-group">
                {{form.login(cass="btn btn-outline-info")}}
            </div>
        </form>
    </div>

{% endblock content %}

app/templates/register.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <legend> Register </legend>
            <div class="form-group">
                {{form.username.label(class="form-control-label")}}
                {{form.username(class="form-control form-control-lg")}}
            </div>
            <div class="form-group">
                {{form.email.label(class="form-control-label")}}
                {{form.email(class="form-control form-control-lg")}}
            </div>
            <div class="form-group">
                {{form.password.label(class="form-control-label")}}
                {{form.password(class="form-control form-control-lg")}}
            </div>
            <div class="form-group">
                {{form.submit(cass="btn btn-outline-info")}}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        Already have an account? <a href="{{ url_for('users.login')}}"> signin </a>
    </div>
{% endblock content %}